name: Trading Bot
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # Fix for Error 128
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run Bot
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python live.py

      - name: Save State
        run: |
          git config --global user.name "TradingBot"
          git config --global user.email "bot@github.com"
          git add trading_state.json trading_journal.csv
          git commit -m "Update logs [skip ci]" || echo "No changes"
          git push origin main
